### ISSUE TITLE
(undocumented) Events missing

### ISSUE THREAD

**Issue by fgather** [maxill1/node-red-contrib-volumio#1]
Hi,

thank you for your great plugin. However, I stumbled upon the issue that some useful but undocumented events are filtered out by the node:

e.g. the really helpful "replaceAndPlay" which is undocumented, but also "removeFromQueue", which is a documented function. 

a list of more events can be found here: 
https://github.com/volumio/Volumio2/blob/4cd303fe8a5e4990245336d08a213c7da7a59196/app/plugins/user_interface/websocket/index.js#L242

do you plan on adding those? Or maybe add a possiblity to send them directly in a passthrough mode?

**Comment by maxill1** [comment]
In theory the node works natively as passthrough and allow you to define an event and a pushEvent.
If you provide only the event, the pushEvent will be decoded from an internal mapping of known event==>pushEvent:
- play ==> pushState
- pause ==> pushState
- prev ==> pushState
- next ==> getSpushStatetate
- setRepeat ==> pushState
- setRandom ==> pushState
- volume ==> pushState
- mute ==> pushState
- unmute ==> pushState
- getQueue ==> pushQueue
- playPlaylist ==> pushQueue
- playFavourites ==> pushQueue
- addToQueue ==> pushState
- getState ==> pushState
- getBrowseSources ==> pushBrowseSources
- browseLibrary ==> pushBrowseLibrary
- getMultiRoomDevices ==> pushMultiRoomDevices
- search ==> pushBrowseLibrary

If you provide a "not known event" you **must** provide also the pushEvent or the palette node won't know where to listen for a response from volumio, and you will get this error:
![image](https://user-images.githubusercontent.com/367042/65822240-bb51df00-e240-11e9-9ca0-ba814083eda6.png)

Nothing prevent you from using a custom event==>pushEvent, but you must know what to listen to, in your case just add "pushState" as "pushEvent" and it works (tested :D)
```
{
    "event": "replaceAndPlay",
    "pushEvent": "pushState",
    "data": {
        "service": "mpd",
        "type": "song",
        "title": "My song",
        "artist": "My artist",
        "album": "My album",
        "uri": "music-library/NAS/myFile.mp3",
        "albumart": "myalbumart"
    }
}
```

Actually I don't have much time right now to map all known commands, but any PR will be welcome.
