### ISSUE TITLE
Volume Control

### ISSUE THREAD

**Issue by SkyRalf** [maxill1/node-red-contrib-volumio#2]
Dear "maxill1",

thank you very much for creating this very exciting NR palette.
It fits my needs to control Volumio perfectly except for the control of volume.
For hours I try to create an flow on how to control volume via NR.
I am new to NR, *.js etc. and I am not succeeding.
I have tried to use Websocket-API and socket.io but my knowledge in this direction is very  limited. 
Would you be so kind and give me an idea on how to go about controlling volume.
Thank you very kindly.

**Comment by maxill1** [comment]
sorry for the delay.

Volume control works for me.

In the following example i put 
`{"event":"volume","data":50}`
in "volume 50" palette (as msg.payload)

![image](https://user-images.githubusercontent.com/367042/65822062-8e9cc800-e23e-11e9-9e44-cf2ece9932b4.png)

**Comment by SkyRalf** [comment]
Thanks a million Luca,

it's easy once you know what you are doing - It works like charm.
Best Regards


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am So., 29. Sept. 2019 um 00:09 Uhr schrieb Luca Mazzilli <
notifications@github.com>:
