### ISSUE TITLE
Ask for adding new command: sleep

### ISSUE THREAD

**Issue by whxciotw** [maxill1/node-red-contrib-volumio#3]
Dear maxill1,

this is an excellent palette for volumio and helps me a lot.

And the sleep function is very helpful to me, but unfortunately this palette did not support this yet.
would you please add the new command: Sleep?

thanks.

**Comment by SkyRalf** [comment]
Excuse me please,
It seems you are using NR for controlling Volumio.
Did you manage by any chance to control the volume with this palette?
If so, would you be so kind and let me know how that can be done.
Thank you very much

**Comment by maxill1** [comment]
it should work, use the correct event=>pushEvent from volumio docs:
https://github.com/volumio/Volumio2/wiki/WebSockets-API-Reference
you can setSleep like this (tested and produces and empty response)
```
{
    "event": "setSleep",
    "pushEvent": "pushSleep",
    "data": {
        "enabled": true,
        "time": "12:00"
    }
}
```
and verify like this:

```
{
    "event": "getSleep",
    "pushEvent": "pushSleep"
}
```
