### ISSUE TITLE
Send Playlist or Album from Spotify on Volumio

### ISSUE THREAD

**Issue by hvddrift** [maxill1/node-red-contrib-volumio#4]
Hi

Great plugin. 

Do you think its possible to have the json data send a spotify command for an Album or Playlist?

If yes, would you mind sharing an example?

**Comment by sdomotica** [comment]
Thsi works for me
`{
    "event": "replaceAndPlay",
    "pushEvent": "pushState",
    "data": {
        "name": "Spotify",
        "service": "spop",
        "uri": "spotify:playlist:xxxxxxxxxxxxxxxxxxxxx"
    }
}`

**Comment by hvddrift** [comment]
Thats great. Thank you.
